# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kleym
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https # Ensure this is the name of the port that exposes HTTPS metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        # The option insecureSkipVerify: true is not recommended for production since it disables
        # certificate verification, exposing the system to potential man-in-the-middle attacks.
        # For production environments, provide trusted metrics certificates and use the
        # config/prometheus/monitor_tls_patch.yaml patch to reference the 'metrics-server-cert' secret.
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kleym
      app.kubernetes.io/component: operator
