# This rule is not used by the project terence itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the terence.sonda.red.sonda.red.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: terence
    app.kubernetes.io/managed-by: kustomize
  name: inferencetrustprofile-editor-role
rules:
- apiGroups:
  - terence.sonda.red.sonda.red
  resources:
  - inferencetrustprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terence.sonda.red.sonda.red
  resources:
  - inferencetrustprofiles/status
  verbs:
  - get
