---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kleym.sonda.red
  resources:
  - inferencetrustbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kleym.sonda.red
  resources:
  - inferencetrustbindings/finalizers
  verbs:
  - update
- apiGroups:
  - kleym.sonda.red
  resources:
  - inferencetrustbindings/status
  verbs:
  - get
  - patch
  - update
