---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - terence.sonda.red
  resources:
  - inferencetrustprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terence.sonda.red
  resources:
  - inferencetrustprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - terence.sonda.red
  resources:
  - inferencetrustprofiles/status
  verbs:
  - get
  - patch
  - update
