apiVersion: kleym.sonda.red/v1alpha1
kind: InferenceIdentityBinding
metadata:
  labels:
    app.kubernetes.io/name: kleym
    app.kubernetes.io/managed-by: kustomize
  name: inferenceidentitybinding-sample
spec:
  # TODO(user): Add fields here
