apiVersion: kleym.sonda.red/v1alpha1
kind: InferenceIdentityBinding
metadata:
  labels:
    app.kubernetes.io/name: kleym
    app.kubernetes.io/managed-by: kustomize
  name: inferenceidentitybinding-sample
spec:
  targetRef:
    apiVersion: v1
    kind: Pod
    name: sample-pod
    namespace: default
  selectorSource: DerivedFromPool
  workloadSelectorTemplates:
    - type: "k8s"
      value: "app=sample"
      
  mode: PoolOnly
  