//go:build !ignore_autogenerated

/*
Copyright 2026 Kalin Daskalov.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingReference) DeepCopyInto(out *BindingReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingReference.
func (in *BindingReference) DeepCopy() *BindingReference {
	if in == nil {
		return nil
	}
	out := new(BindingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputedSpiffeIDStatus) DeepCopyInto(out *ComputedSpiffeIDStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputedSpiffeIDStatus.
func (in *ComputedSpiffeIDStatus) DeepCopy() *ComputedSpiffeIDStatus {
	if in == nil {
		return nil
	}
	out := new(ComputedSpiffeIDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityBoundary) DeepCopyInto(out *IdentityBoundary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityBoundary.
func (in *IdentityBoundary) DeepCopy() *IdentityBoundary {
	if in == nil {
		return nil
	}
	out := new(IdentityBoundary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityBoundaryConflictStatus) DeepCopyInto(out *IdentityBoundaryConflictStatus) {
	*out = *in
	out.BindingRef = in.BindingRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityBoundaryConflictStatus.
func (in *IdentityBoundaryConflictStatus) DeepCopy() *IdentityBoundaryConflictStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityBoundaryConflictStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityBoundaryStatus) DeepCopyInto(out *IdentityBoundaryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityBoundaryStatus.
func (in *IdentityBoundaryStatus) DeepCopy() *IdentityBoundaryStatus {
	if in == nil {
		return nil
	}
	out := new(IdentityBoundaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceIdentityBinding) DeepCopyInto(out *InferenceIdentityBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceIdentityBinding.
func (in *InferenceIdentityBinding) DeepCopy() *InferenceIdentityBinding {
	if in == nil {
		return nil
	}
	out := new(InferenceIdentityBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceIdentityBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceIdentityBindingList) DeepCopyInto(out *InferenceIdentityBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferenceIdentityBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceIdentityBindingList.
func (in *InferenceIdentityBindingList) DeepCopy() *InferenceIdentityBindingList {
	if in == nil {
		return nil
	}
	out := new(InferenceIdentityBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceIdentityBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceIdentityBindingSpec) DeepCopyInto(out *InferenceIdentityBindingSpec) {
	*out = *in
	out.PoolRef = in.PoolRef
	out.IdentityBoundary = in.IdentityBoundary
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceIdentityBindingSpec.
func (in *InferenceIdentityBindingSpec) DeepCopy() *InferenceIdentityBindingSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceIdentityBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceIdentityBindingStatus) DeepCopyInto(out *InferenceIdentityBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdentityBoundary != nil {
		in, out := &in.IdentityBoundary, &out.IdentityBoundary
		*out = new(IdentityBoundaryStatus)
		**out = **in
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]IdentityBoundaryConflictStatus, len(*in))
		copy(*out, *in)
	}
	if in.ComputedSpiffeIDs != nil {
		in, out := &in.ComputedSpiffeIDs, &out.ComputedSpiffeIDs
		*out = make([]ComputedSpiffeIDStatus, len(*in))
		copy(*out, *in)
	}
	if in.RenderedSelectors != nil {
		in, out := &in.RenderedSelectors, &out.RenderedSelectors
		*out = make([]RenderedSelectorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RenderedClusterSPIFFEID != nil {
		in, out := &in.RenderedClusterSPIFFEID, &out.RenderedClusterSPIFFEID
		*out = new(RenderedClusterSPIFFEIDStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceIdentityBindingStatus.
func (in *InferenceIdentityBindingStatus) DeepCopy() *InferenceIdentityBindingStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceIdentityBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferencePoolTargetRef) DeepCopyInto(out *InferencePoolTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferencePoolTargetRef.
func (in *InferencePoolTargetRef) DeepCopy() *InferencePoolTargetRef {
	if in == nil {
		return nil
	}
	out := new(InferencePoolTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedClusterSPIFFEIDStatus) DeepCopyInto(out *RenderedClusterSPIFFEIDStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedClusterSPIFFEIDStatus.
func (in *RenderedClusterSPIFFEIDStatus) DeepCopy() *RenderedClusterSPIFFEIDStatus {
	if in == nil {
		return nil
	}
	out := new(RenderedClusterSPIFFEIDStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenderedSelectorStatus) DeepCopyInto(out *RenderedSelectorStatus) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenderedSelectorStatus.
func (in *RenderedSelectorStatus) DeepCopy() *RenderedSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(RenderedSelectorStatus)
	in.DeepCopyInto(out)
	return out
}
