name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on arc-set-nuc
    runs-on: arc-set-nuc
    container:
      image: golang:1.23
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Running Tests
        run: |
          go mod tidy
          make test
